name: Deploy Website

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: export GT=${{ secrets.GT }}
      - run: export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
      - run: npm install -g npm
      - run: npm install -g firebase-tools
      - run: export GT=${{ secrets.GT }} && npm install -f
      - run: export GT=${{ secrets.GT }} && export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} && npm run deploy:web:ci
        env:
          #           FIREBASE_TOKEN:  ${{ secrets.FIREBASE_TOKEN }}
          GRT: ${{ secrets.GITHUB_TOKEN }}
